version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container-addifly
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anonymous
      POSTGRES_DB: company
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "4321:5432"
    restart: always

volumes:
  postgres_data: